blank_issues_enabled: true
contact_links:
  - name: Soporte
    url: https://github.com/Kolozuz/unio_tools
    about: Please ask and answer questions here.
  - name: Security Bug Bounty
    url: https://github.com/Kolozuz/unio_tools
    about: Please report security vulnerabilities here.