name: "✨Feature request"
description: Suggest an idea for this project
title: "✨ [Feature]: "
labels: ["enhancement"]
projects: Lana-Software/3
assignees: 
  - Kolozuz

body:
  - type: markdown
    attributes:
      value: |
         **Thanks for taking the time to submit your suggestion! :heart:**
         >[!NOTE]
         >Remember that you can use markdown formatting.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature you're proposing.
      options:
      - label: I've checked that this issue doesn't already exist.
        required: true
  - type: textarea
    id: desc
    attributes:
      label: Description
      description: Describe your idea/suggestion, how do you expect it to be? the more specific the better.
      placeholder: |
        ex. I want to have ponies that fly across the page...
        Because ponies are cool...
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: "Current Behaviour / Implementation"
      description: |
          Does your idea or something similar already exists? Tell us why it should change or why it doesn't meet the requirements.
          Type None if nothing like this exists
      placeholder: |
          The current implementation sucks cause there aren't ponies, just rats! 
          and rats make me crazy...
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: "Additional Context / Notes"
      description: Information that may be useful for the implementation of this feature, add any other context or screenshots or little code snippets about the feature request here.
      placeholder: |
          > they locked me in a room, a rubber room..
